# Generated by Django 5.1.5 on 2026-02-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='notes',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default=0, upload_to='player_pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
