# Generated by Django 5.2.11 on 2026-02-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_notes_player_age_player_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=0, help_text='cm '),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both Foot', 'Both Foot')], default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=0, help_text='kg'),
        ),
    ]
